[build-system]
requires = ["setuptools>=42", "setuptools_scm[toml]>=3.4", "wheel", "Cython>=0.29.17,<=0.29.36"]

[tool.setuptools_scm]
write_to = "src/version.h"
write_to_template = '#define PYMSSQL_VERSION "{version}"'
#local_scheme = "no-local-version"
local_scheme = "no-local-version"
